// <auto-generated />
using System;
using GameManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameManager.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230916172238_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Connect4Game.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Matrix");

                    b.HasKey("Id");

                    b.ToTable("Board");
                });

            modelBuilder.Entity("Connect4Game.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BoardId");

                    b.Property<int>("CurrentPlayer");

                    b.Property<TimeSpan>("GameDuration");

                    b.Property<int>("PlayerId");

                    b.Property<DateTime>("StartTime");

                    b.Property<int>("Status");

                    b.HasKey("GameId");

                    b.HasIndex("BoardId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Connect4Game.Move", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ColumnNumber");

                    b.Property<int?>("GameId");

                    b.Property<int>("Player");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Move");
                });

            modelBuilder.Entity("GameManager.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Connect4Game.Game", b =>
                {
                    b.HasOne("Connect4Game.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId");

                    b.HasOne("GameManager.Models.Player")
                        .WithMany("Games")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Connect4Game.Move", b =>
                {
                    b.HasOne("Connect4Game.Game")
                        .WithMany("Moves")
                        .HasForeignKey("GameId");
                });
#pragma warning restore 612, 618
        }
    }
}
