apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect4-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect4-db
  template:
    metadata:
      labels:
        app: connect4-db
    spec:
      containers:
      - name: connect4-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          value: "YourStrong!1Password"
        - name: ACCEPT_EULA
          value: "Y"
