apiVersion: v1
kind: Service
metadata:
  name: connect4-server-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30080
  selector:
    app: connect4-server
